# Generated by Django 3.0.5 on 2021-07-30 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0009_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='category',
            field=models.CharField(choices=[('Maestranza', 'Maestranza'), ('Vehiculos pesados', 'Vehiculos pesados'), ('Motocicletas', 'Motocicletas'), ('Vehiculos livianos', 'Vehiculos livianos')], max_length=50),
        ),
    ]
