# Generated by Django 3.0.5 on 2021-08-02 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0010_auto_20210730_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('approved', 'approved'), ('Reparando', 'Reparando'), ('Reparacion Finalizada', 'Reparacion Finalizada'), ('Liberado', 'Liberado')], default='Pendiente', max_length=50, null=True),
        ),
    ]
