# Generated by Django 3.0.5 on 2021-08-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0012_auto_20210802_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado'), ('Reparando', 'Reparando'), ('Reparacion Finalizada', 'Reparacion Finalizada'), ('Liberado', 'Liberado')], default='Pendiente', max_length=50, null=True),
        ),
    ]
